version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "7071:7071"
    environment:
      - NODE_ENV=development
      - PORT=7071
      - FRONTEND_URL=http://localhost:3000
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:7071
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
    command: npm run dev
